config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  # get 'cocktails', to: 'cocktails#index'
  # get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  # get 'cocktails/new', to: 'cocktails#new'
  # post 'cocktails', to: 'cocktails#create'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  # get 'cocktails/:id/doses/new', to: 'doses#new'
  # post 'cocktails/:id/doses', to: 'doses#create'
  delete 'doses/:id', to: 'doses#destroy', as: 'dose'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_back fallback_location: @cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div id="cocktail-homepage">
  <div class="mt-0 banner">
    <h1 class="banner-text">
      best drinks around
    </h1>
  </div>
      <h2 class="title">cocktails list</h2>
    <div class="container card-box">
      <% @cocktails.each do |cocktail| %>
          <%= link_to cocktail do %>
              <div class="cocktail-card">
                <% if cocktail.photo.file.nil? %>
                  <%= image_tag ("blank-cocktail.jpg"), class: "cocktail-img" %>
                <% else %>
                  <%= cl_image_tag cocktail.photo, class: "cocktail-img" %>
                <% end %>
                <div class="cocktail-card-text">
                  <h4>
                    <%= cocktail.name %>
                  </h4>
                </div>
              </div>
          <% end %>
      <% end %>
  </div>
  <%= link_to new_cocktail_path do %>
    <p class="btn btn-success new-button">New Recipe</p>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>New Cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <div class="text-center">
      <%= f.button :submit, class: "btn-success" %>
    </div>
  <% end %>
  <div class="text-center", >
    <%= link_to "Back to list", cocktails_path, class: "btn btn-success", id:"margin-top-btn" %>
  </div>

</div>

app/views/cocktails/show.html.erb
<div class="container text-center">
  <h1><%= @cocktail.name %></h1>
  <% if @cocktail.photo.file.nil? %>
    <%= image_tag ("blank-cocktail.jpg"), height: 300, crop: :fill %>
  <% else %>
    <%= cl_image_tag @cocktail.photo, height: 300, crop: :fill %>
  <% end %>
  <h2>doses</h2>
    <% @cocktail.doses.each do |dose| %>
        <p>
        <%= dose.description %> - <%= dose.ingredient.name  %>
          <%= link_to "X", dose, method: :delete, data: {confirm: "Are you sure?"} %>
        </p>
    <% end %>
<div id="margin-bottom-btn">
  <%= link_to "Add dose", new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>

  <%= link_to "Back to list", cocktails_path, class: "btn btn-success" %>

  <%= link_to "Delete", @cocktail, method: "delete", class: "btn btn-success" %>

</div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>New Dose - <%= @cocktail.name %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.button :submit %>
  <% end %>

  <%= link_to @cocktail do %>
    <p class"btn btn-success">Back to <%= @cocktail.name %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCoktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body class="keepfooter">
    <%= render "./shared/navbar" %>
    <%= yield %>
    <%= render "./shared/footer" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <%= link_to root_path do %>
    <h3>
      <i class="fas fa-glass-martini" id="navcolor"></i>
    </h3>
  <% end %>
  </div>
</div>